<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Seguridad\UsuarioDetalle.razor" />
    <Content Remove="Seguridad\UsuarioDetalleRoles.razor" />
    <Content Remove="Seguridad\UsuariosList.razor" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="3.2.0" />
    <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" Version="5.6.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.19.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Radzen.Blazor" Version="6.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ProyectoParLibs">
      <HintPath>Dll\ProyectoParLibs.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>