<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="3.2.0" />
    <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" Version="5.6.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PortalNominaLibs">
      <HintPath>..\Dlls\PortalNominaLibs.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>